### ISSUE TITLE
Build inside docker container

### ISSUE THREAD

**Issue by JoyceBabu** [OSTC/php-sdk-binary-tools#26]
Will it be possible to create a docker image with VS Community edition for building PHP extension?

**Comment by weltling** [comment]
So far I see, VS 2017 is permitted for containers, thus it could be used at least to build PHP 7.2. Currently, we have a centralized build bot for PECL releases, targeting all the stable branches. Many projects also use AppVeyor for QA, which supports more VS versions and allows to push artifacts.

Depending on your use case, seems you could use Docker for the builds. Fe if you only target 7.2. Otherwise, a normal VM or AppVeyor seems more promising in the practical sense.

Thanks.

**Comment by JoyceBabu** [comment]
From what I have read so far, it is not possible to install the full Visual Studio (Community Edition) into a docker container. But it is possible to install Build Tools. Would that suffice?

**Comment by JoyceBabu** [comment]
It worked with build tools in docker container. Thank you.

**Comment by weltling** [comment]
Yes, Build Tools should be fine. Unfortunately this part is tested purely, as the most build bots, etc. have full VS installs. Nevertheless, good to hear it works :)

Thanks.
