### ISSUE TITLE
Where to update phpsdk_deps?

### ISSUE THREAD

**Issue by kohldampfer** [OSTC/php-sdk-binary-tools#31]
I have problems to understand, where to run this command `phpsdk_deps --update --branch master` (in the paragraph **Basic usage example**). 

When I understand the paragraph correct, then I should be in the directory `php-src` and then run this command `..\path\to\phpsdk_deps --update --branch master`. Is this correct? Or should I be outside of the `php-src` directory?

**Comment by weltling** [comment]
It is possible both ways. While in `php-src`, many things can be guessed by the tool, based on the information from the source code and from the environment. In that case, almost anything except the actual command option like `--update` can be left aside. Otherwise, additional switches must be used, so the tool has the exact information about what it is required to do. The example from the README.md tells `cd php-src` before, so the very minimum on the information is required.

Thanks.

**Comment by weltling** [comment]
The issue seems resolved, thus closing.

Thanks.
