### ISSUE TITLE
The updated plan for https://windows.php.net/downloads/php-sdk/deps-7.1-vc14-x64.7z

### ISSUE THREAD

**Issue by lucastruong** [OSTC/php-sdk-binary-tools#33]
Hi all,

I have a question to ask. The archives (5.6, 7.0) are updated in 2018. 
But only the 7.1 archive is not updated. What is the reason for this?

Ref. https://windows.php.net/downloads/php-sdk/
 3/30/2018  3:49 AM     27645065 deps-5.6-vc11-x64.7z
 3/30/2018  3:49 AM     25876397  deps-5.6-vc11-x86.7z
 2/27/2018 10:35 PM     39857610  deps-7.0-vc14-x64.7z
 2/27/2018 10:35 PM     37222501  deps-7.0-vc14-x86.7z
 **4/27/2017  8:18 PM     40213850   deps-7.1-vc14-x64.7z
 4/27/2017  8:17 PM     37479597   deps-7.1-vc14-x86.7z**

Thank all.

**Comment by weltling** [comment]
Thanks for the question. Because of AppVeyor we need to maintain the dependency lists for 7.1 for the SDK anyway. The archives for versions lower 7.1 however need to be updated separately. One can fetch the 7.1 dependencies using `phpsdk_deps` from the new binary SDK for now. The deps otherwise might be updated after the next release.

Thanks.

**Comment by weltling** [comment]
The updated packages are uploaded.

Thanks.
