### ISSUE TITLE
How to re-compile only specific extensions?

### ISSUE THREAD

**Issue by leeoniya** [OSTC/php-sdk-binary-tools#4]
@weltling 

Hi, this might be a bit off-topic, but figured i'd ask in case the answer was quick.

I'd like to (re)compile `php_sqlite3.dll` and/or `php_pdo_sqlite.dll` with some of the amalgamation [1] extensions enabled. Specifically `FTS5` [2], but I assume the process would be the same for others, too. What would be the steps involved in building just those php extensions (with the needed sqlite extensions) without having to recompile all of php in the process?

let's assume latest stable `7.*` release and `new_binary_tools` branch

thanks if you can help :)

[1] https://www.sqlite.org/amalgamation.html
[2] https://www.sqlite.org/fts5.html

**Comment by weltling** [comment]
In general how to rebuild only the exts you're interested on - if you want them to be a replacement for the standard build, be sure they're supplied shared. Otherwise, you'll need the whole core rebuild. It can be done, but on the costs of losing PGO optimizations. With shared - just take same branch, so ABI is compatible. Do a minimal configure with the only exts of interest and replace the DLLs in the standard distribution. Fe, you want to replace a shared ext in 7.0.x, so
- checkout some 7.0.x release
- apply patches, etc. to ext-you-want
- buildconf && configure --disable-all --enable-cli --enable-ext-you-want=shared
- nmake
- replace php_ext_you_want.dll in the standard distro (or possibly the dependency DLLs as well)

About libsqlite - the FTS plugins are disabled by default. I see, that the only enabled one in PHP is FTS3, but seems we've missed the others. I've added the flags enabling FTS4 and FTS5, so you can build yourself or extract the DLLs from a [snapshot build](http://windows.php.net/snapshots/). And yes - you should have reported an issue on bugs.php.net about the missing plugins. Please handle it that way next time.

Thanks.

**Comment by leeoniya** [comment]
I assumed that the bundled sqlite was compiled without extensions, so did not think the absence of FTS5 qualified as a bug, otherwise I would have gone through bugs.php.net.

Thanks for your help.

**Comment by weltling** [comment]
Yeah, the FTS plugins are disabled by default in SQLite3 itself. FTS3 was already activated, but i guess, since no on was asking, nobody took care of the updates. Anyway, a question about the build would belong here or ML, but about the missing feature to the BT :) The enabled FTS4 and FTS5 will go through the usual QA and appear in the next RC. If there are no issues, it's likely to stay by default then.

Btw, if you use the new SDK, it'd be great to hear if there are some issues.

Thanks.

**Comment by leeoniya** [comment]
> The enabled FTS4 and FTS5 will go through the usual QA and appear in the next RC

As far as initial QA from me, I switched to http://windows.php.net/snapshots/#php-7.0-nts-windows-vc14-x64 (re87daf3) and no issues so far.

> Btw, if you use the new SDK, it'd be great to hear if there are some issues.

Maybe not an issue with the tools but me...but I tried to compile https://pecl.php.net/package/mailparse against `7.1` and it didnt error (or just swallowed it) but also didn't produce a `dll` anywhere. I followed [1] and used this SDK. Another thing is that the builds always compile TS releases, dunno how to switch it over to NTS.

[1] https://wiki.php.net/internals/windows/stepbystepbuild#building_pecl_extensions

**Comment by weltling** [comment]
Good to know, already a good sign you see no issues with libsqlite :)

With mailparse - not sure it's something about SDK, there's no change in relevant area. Sounds more like config issue or similar. You can usually check `configure --help` for more options, save the configure output for possible configure errors, and save the build output to check for errors afterwards. If there is an issue, please handle it in a separate ticket on BT.

Thanks.
