### ISSUE TITLE
Add tee(1) to new_binary_tools

### ISSUE THREAD

**Issue by cmb69** [OSTC/php-sdk-binary-tools#5]
It would be great to have tee(1) to be guaranteed to be available, so the [mail() related PHPTs](http://lxr.php.net/xref/PHP-7.0/ext/standard/tests/mail/) could finally be unified for Linux and Windows. The current situation where one has to employ ext/imap to test mail() on Windows is very unfortunate.

**Comment by weltling** [comment]
Thanks for checking, Christoph. Itself, the tee utility would work as expected. But, the redirection like `>/dev/null` wouldn't when run through cmd.exe. Taking the fact, sendmail_path is a system option, ini_set() wouldn't work as well, so it couldn't be done conditionally as `>nul` within the test body. So we'd still need to duplicate the test, or find another way to trick it. Also, still the SMTP part wouldn't be tested, even if we'd get it to work. I've added tee.exe anyway, probably need to think a bit more about how to make it useful for the tests.

Thanks.

**Comment by cmb69** [comment]
Oh, I've totally forgotten the `/dev/null` vs. `NUL` issue. Maybe we could use `cat - > file/name` instead of `tee`? Trying that for `ext/standard/tests/mail/mail_basic.phpt` works on Linux and Windows. That would require cat(1), though.

And yes, it's probably best to have actual SMTP tests on Windows, but nonetheless it would be great to have _all_ Unix mail() tests also running on Windows (AFAIR, several tests are Unix only currently).

Anyhow, thanks for adding tee(1) so quickly. :-)

**Comment by weltling** [comment]
Well, thanks you for checking the new SDK! Still fixing some small bugs and preparing for the build hosts, otherwise it might be already ok for master at least.

I thought more about touching the run-tests.php. Maybe introducing some template var, like PHP_TEST_NULL_DEVICE and/or some others alike, so it would be auto replaced on the corresponding platform. But just need an idea, how to design that. It doesn't look to be worth it to fork the whole test in this case.

The tee  command itself, however, can be useful independent from that. Cat should work as well, can be added, if we need it. What I'd basically see with the tools - only adding those that are obviously needed or usefil, avoiding conflicting commands as everything is directly on the path and still keeping the SDK package small.

Thanks.
