### ISSUE TITLE
What's the problem? unrecognized %destructor

### ISSUE THREAD

**Issue by ghost** [OSTC/php-sdk-binary-tools#6]
```
d:\php-sdk\phpdev\vc14\x64\php-src-php-7.0.14>nmake

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        bison.exe --output=Zend/zend_ini_parser.c -v -d -p ini_ Zend/zend_ini_parser.y
zend/zend_ini_parser.y:295: unrecognized: %destructor
zend/zend_ini_parser.y:295:    Skipping to next %
NMAKE : fatal error U1077: 'd:\php-sdk\bin\\..\bin\bison.exe' : return code '0x1'
Stop.
```

**Comment by weltling** [comment]
Thanks for the report. Could it be, that you're on a DBSC system? Otherwise, I see that the old SDK is used. It would make sense to check with the new SDK branch as well.

Thanks.

**Comment by ghost** [comment]
windows 10，the sdk download from php.net, https://wiki.php.net/internals/windows/stepbystepbuild 

http://windows.php.net/downloads/php-sdk/

**Comment by weltling** [comment]
Ups, DBCS system i meant. Or simply - is your default system codepage some of 932, 936 or alike? That is known to cause issues with some source files and tools, including Visual Studio. It might be good to fix this, but has not a big impact. The compilation on SBCS systems isn't known to cause any issues, so switching the code page to something like 437 should be fine.

Otherwise, the new_binary_tools branch is rather in focus now, about to move to master soon. It also has newer tools, so might work better.

Thanks.

**Comment by ghost** [comment]
936, windows with chinese version. tried new_binary_tools. working well. Did it support VisualStudio 2017 RC?

**Comment by weltling** [comment]
Ah, ok then. So it indeed seems to be the codepage issue, i've met it sometimes with Korean and Japanese versions as well. With the legacy SDK, it's probably ok to fail in this constellation. Switching to 437 or alike should help, if the legacy SDK has to be used. The new branch is based on the tools from the current MSYS2, so that probably explains it. I think this one can be closed as well.

OFC you can use 2017, it's even already added into the build system. But with the SDK you'll need to go the old way as in the step by step doc. The new SDK reads all the data from the registry and the Visual Studio RC versions use separate registry entries, so they don't break the existing stable installs. OFC it'll work out of the box with 2017 stable with the `phpsdk-starter.bat`. We've no info yet, whether 2017 is going to be used for next PHP and all the deps are vc14 now, so be aware. But otherwise - just use the new SDK, but go the old way with vcvarsall.bat and co, to get the vc15 environment set.

Thanks.

**Comment by weltling** [comment]
Closing this one, since there's no issue with the new SDK.

Thanks.
