### ISSUE TITLE
Bundle PHP 7.4

### ISSUE THREAD

**Issue by mvorisek** [OSTC/php-sdk-binary-tools#67]
PHP 7.4 is out and it is the latest stable, so this version should be also bundled.

**Comment by cmb69** [comment]
What do you mean by "be bundled"?

**Comment by cmb69** [comment]
Ah, you're referring to https://github.com/microsoft/php-sdk-binary-tools/tree/master/bin/php. I don't see any need to bundle PHP 7.4 in addition. We may want to upgrade some time in the not too distant future, though.

**Comment by mvorisek** [comment]
@cmb69 Yes, the PHP in the `bin/` dir. For example, we build some Windows extensions using this repo and then do quick testing using the bundled PHP. And currently it fails, as the PHP ext. API versions differ (we build with the latest/7.4 PHP version).

**Comment by mvorisek** [comment]
@weltlingweltling can you please upgrade the bundled PHP as in the past? - https://github.com/microsoft/php-sdk-binary-tools/commits/master/bin/php Thanks.

**Comment by mvorisek** [comment]
@weltling  can you please upgrade the bundled PHP as in the past? - https://github.com/microsoft/php-sdk-binary-tools/commits/master/bin/php Thanks.

**Comment by cmb69** [comment]
I have upgraded to PHP 7.3.13 now. To clarify: the SDK bundles a rather minimal PHP versions so that contained scripts written in PHP can be run. This bundled PHP should never be used to run on a public Webserver, and even for actual development purposes I strongly recommend to either use a self built PHP or to use a [full release version](https://windows.php.net/downloads/releases/).
